<?php
 echo '
 <center><h1>Welcome to the Admission Portal - 2013</h1></br></center>';
 include("side_menu.php");
 echo '<div id=article>';
 select_branch();
 echo '<p>Best site over all providing the utmost information about almost all the colleges in India in Engineering, Medical and Management streams.</p><p>This site provides you the complete information about a college before joining them.</p><p>Best site over all providing the utmost information about almost all the colleges in India in Engineering, Medical and Management streams.</p><p>This site provides you the complete information about a college before joining them.</p><p>Best site over all providing the utmost information about almost all the colleges in India in Engineering, Medical and Management streams.</p><p>This site provides you the complete information about a college before joining them.</p><p>Best site over all providing the utmost information about almost all the colleges in India in Engineering, Medical and Management streams.</p><p>This site provides you the complete information about a college before joining them.</p><p>Best site over all providing the utmost information about almost all the colleges in India in Engineering, Medical and Management streams.</p><p>This site provides you the complete information about a college before joining them.</p><p>Best site over all providing the utmost information about almost all the colleges in India in Engineering, Medical and Management streams.</p><p>This site provides you the complete information about a college before joining them.</p><p>Best site over all providing the utmost information about almost all the colleges in India in Engineering, Medical and Management streams.</p><p>This site provides you the complete information about a college before joining them.</p><p>Best site over all providing the utmost information about almost all the colleges in India in Engineering, Medical and Management streams.</p><p>This site provides you the complete information about a college before joining them.</p><p>Best site over all providing the utmost information about almost all the colleges in India in Engineering, Medical and Management streams.</p><p>This site provides you the complete information about a college before joining them.</p><p>Best site over all providing the utmost information about almost all the colleges in India in Engineering, Medical and Management streams.</p><p>This site provides you the complete information about a college before joining them.</p>';
 go_top();
 echo '</div>';
?>